GOOGLE_CHAT_PULL_REQUEST_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAwSc8L-Y/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=OB50ZiNTRP93FjQnJTNJ2OdUa7j0QZt61AOssLTFWJ8%3D

name: chat-pull-request
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-chat@v1
        with:
          url: ${{ GOOGLE_CHAT_PULL_REQUEST_WEBHOOK_URL }}
